name: Tests

on:
  push:
    branches: [ main ]
    paths:
    - 'pkg/**'
    - '*.go'
    - 'go.*'
  pull_request:
    branches: [ main ]
    paths:
    - 'pkg/**'
    - '*.go'
    - 'go.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - id: binaries
        run: |
          echo "::set-output name=local-binaries::$GITHUB_WORKSPACE/bin"
          echo "::set-output name=vaultwarden-version::1.21.1"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...